services:
  postgres:
    build:
      context: ./Database
      dockerfile: Dockerfile.postgres
    restart: always
    env_file:
      - ./Database/.env
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s


  api-gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - main-service
    networks:
      - api-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx

  auth-service:
    build:
      context: ./Authentication
      dockerfile: Dockerfile.auth
    env_file:
      - ./Database/.env
      - ./Authentication/.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./Authentication:/app/Authentication
    command: ["uvicorn", "Authentication.auth_server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - api-network
    depends_on:
      postgres:
        condition: service_healthy

  main-service:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - ./Database/.env
      - ./Authentication/.env
      - ./.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MCP_SERVER_HOST: localhost
      CHROMA_PERSIST_DIR: ./chroma_db
    volumes:
      - chroma_data:/app/chroma_db
      - ./outputs:/app/outputs
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001"]
    networks:
      - api-network
    depends_on:
      postgres:
        condition: service_healthy
      auth-service:
        condition: service_started

networks:
  api-network:
    driver: bridge

volumes:
  nginx_logs:
  pgdata:
  chroma_data:
