FROM python:3.10-slim

WORKDIR /app

COPY requirements_auth.txt .
RUN pip install --no-cache-dir -r requirements_auth.txt

COPY . ./Authentication/

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["python", "-m", "Authentication.auth_server"]
